export default {
  'tips.collateral.node.action': 'I agree',
  'tips.collateral.node.title': 'What will happen after collateralizing node?',
  'tips.collateral.node.tips.1':
    'When a node is collateralized, the beneficiary becomes the smart contract address of the platform and the proceeds generated by the node are mailed to the platform.',
  'tips.collateral.node.tips.2':
    'The user can release collateral to recover the node privileges and node revenue.',
  'tips.collateral.node.tips.3':
    'If the user has not paid off the debt at the time of release collateral, the platform will automatically deduct the corresponding pledged coins and then return the node privileges and node revenue.',
};
